# Generated by Django 4.0 on 2022-07-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_name', models.CharField(help_text='bitte eine Stellengröße eingeben', max_length=200)),
            ],
            options={
                'verbose_name': 'dimension',
                'verbose_name_plural': '2. Stellengrößen',
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(help_text='bitte eine Regelgröße eingeben', max_length=200)),
            ],
            options={
                'verbose_name': 'factor',
                'verbose_name_plural': '1. Regelgrößen',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': '5. Nutzerdaten',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('impl_level', models.PositiveSmallIntegerField(default='')),
                ('showing', models.BooleanField(default=True)),
                ('factor', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='polls.factor')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': '3. Fragebögen',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('impl_level', models.PositiveSmallIntegerField(default=0)),
                ('added_to_survey', models.BooleanField(default=True)),
                ('factor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.factor')),
                ('related_survey', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.survey')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': '4. Fragen',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.factor')),
                ('related_question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
                ('related_survey', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.survey')),
                ('stellengröße', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.dimension')),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': '5. Resultate',
            },
        ),
    ]
