# Generated by Django 4.0 on 2022-07-28 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_factor_alter_survey_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='factor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.factor'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='factor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.factor'),
        ),
    ]
